In [1]:
import numpy
import pandas
import joblib
numpy.set_printoptions(threshold=10)

import matplotlib.pyplot
%matplotlib inline

# Instructions

- Read **the train data** from the CSV file and properly set the index
- Use `joblib` to load the trained model and print out the model parameters
- Again, print out those model parameters

In [2]:
data_train = pandas.read_csv('./data/features.train.csv').set_index('id')
data_train

feature_1   label
id                    
253     1.4920  1.0676
667    -0.9317  0.8359
85     -1.4077 -1.6642
969     2.2750  0.7641
75     -2.7649 -0.0689
..         ...     ...
835    -0.1237 -0.8241
192    -1.8828 -1.0807
629    -2.1139 -2.9819
559     2.3218  1.2918
684    -2.3413 -1.0121

[750 rows x 2 columns]

In [3]:
model = joblib.load('model/model.joblib')
model

LinearRegression()

In [4]:
print(f"model.coef_     : {model.coef_}")
print(f"model.intercept_: {model.intercept_}")

model.coef_     : [0.60281947]
model.intercept_: 0.06803677794930316


# Instructions

- Type the equation of the mean squared loss (mse) the using Markdown language
  - Advanced: negative log likelihood of the Gaussian model may be used
- Write a function that takes a `numpy.array` of model parameters as input and returns the mean squared loss 
- Evaluate the mean squared loss at $[0., 0.]$
  - Hint: it should return 2.1764
- Evaluate the mean squared loss at the model parameters
  - Hint: it should return 1.0652
- Evaluate and compare the mean squared loss at some other parameters
  - Note that all the losses of the other parameters are no less than that of the trained parameters

$\mathrm{mse_{data}(intercept\_and\_coefs)} = \dfrac{1}{N} \cdot \sum_{i} \Big\{ y_i - (w_0 + w_1 x_1) \Big\}^2$

In [5]:
def calculate_mse(intercept_and_coefs):
    mse = (
        data_train[['feature_1']]
        .dot(intercept_and_coefs[1:])
        .add(intercept_and_coefs[0])
        .sub(data_train['label'])
        .apply(numpy.square)
        .mean()
    )
    
    return mse


In [6]:
calculate_mse([0., 0.])

2.176447902906667

In [7]:
calculate_mse([0.0680, 0.6028])

1.065228974278216

In [8]:
for i in range(10):
    parameters = numpy.random.random(2)
    mse = calculate_mse(parameters)
    print(f"calculate_mse({parameters}) = {mse:.4f}")
                        

calculate_mse([0.17786608 0.11651247]) = 1.7927
calculate_mse([0.63695246 0.43015369]) = 1.4736
calculate_mse([0.91965521 0.66858314]) = 1.8070
calculate_mse([0.08043573 0.50316179]) = 1.0955
calculate_mse([0.85596056 0.34369423]) = 1.8779
calculate_mse([0.3309728  0.24311066]) = 1.5218
calculate_mse([0.39319629 0.05457077]) = 2.0736
calculate_mse([0.00756478 0.864065  ]) = 1.2753
calculate_mse([0.4308294  0.79473335]) = 1.3129
calculate_mse([0.61728661 0.35226802]) = 1.5494


# Instructions

- Linear regression is one of the simplest models that exhibit closed-form parameter estimation
- Type the equation of the closed-form parameter estimate $\mathbf{w}$ in terms of $\mathbf{X}, \mathbf{y}$, assuming that
  - $\mathbf{X} = [1, \mathrm{feature\_1}]$
  - $\mathbf{y} = [\mathrm{label}]$
  - $\mathbf{w} = [\mathrm{intercept\_}, \mathrm{coefs\_}]$
- Now, **manually calculate** the parameter estimate from the training data
  - Hint: use `.coef_`, `.dot`
- Verify that the parameter estimates from the trained model and manual calculations are equal
  - Hint: use `numpy.allclose`




$\mathbf{w} = (\mathbf{X}^{T} \mathbf{X})^{-1} \mathbf{X} \mathbf{y}$

In [9]:
X = numpy.concatenate([
    numpy.ones((data_train.shape[0], 1)), 
    data_train[['feature_1']].to_numpy()],
    axis=1
)
X

array([[ 1.    ,  1.492 ],
       [ 1.    , -0.9317],
       [ 1.    , -1.4077],
       ...,
       [ 1.    , -2.1139],
       [ 1.    ,  2.3218],
       [ 1.    , -2.3413]])

In [10]:
y = data_train['label'].to_numpy()
y

array([ 1.0676,  0.8359, -1.6642, ..., -2.9819,  1.2918, -1.0121])

In [11]:
w = numpy.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
w

array([0.06803678, 0.60281947])

In [12]:
numpy.allclose(w, [model.intercept_, model.coef_[0]])

True